#                                                                        #
# Routes configuration                                                   #
#                                                                        #
# This file contains the configuration for the MVC router.               #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the Flow manual for possible configuration options.    #
#                                                                        #

##
# Subroutes from the Welcome package.
#
# If the package "Welcome" is installed, its fallback route will point to an
# informative welcome screen.

-
  name: 'MimerApi'
  uriPattern: '<MimerApiSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    MimerApiSubroutes:
      package: Langeland.Mimer


##
# Flow subroutes
#

-
  name: 'Flow'
  uriPattern: '<FlowSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FlowSubroutes:
      package: TYPO3.Flow
