<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150917091128 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE langeland_mimer_domain_model_node (identifier VARCHAR(32) NOT NULL, created DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_210E3080772E836A (identifier), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE langeland_mimer_domain_model_sample (identifier INT UNSIGNED AUTO_INCREMENT NOT NULL, node VARCHAR(32) DEFAULT NULL, time DATETIME NOT NULL, data LONGTEXT NOT NULL COMMENT '(DC2Type:array)', INDEX IDX_CF8EAB5F857FE845 (node), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE langeland_mimer_domain_model_sample ADD CONSTRAINT FK_CF8EAB5F857FE845 FOREIGN KEY (node) REFERENCES langeland_mimer_domain_model_node (identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE langeland_mimer_domain_model_sample DROP FOREIGN KEY FK_CF8EAB5F857FE845");
		$this->addSql("DROP TABLE langeland_mimer_domain_model_node");
		$this->addSql("DROP TABLE langeland_mimer_domain_model_sample");
	}
}